;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Fire.Fireball",DevComment="Fireball ability tag")
+GameplayTagList=(Tag="Ability.Magic.Fire.Fireball",DevComment="Primary Fireball ability")
+GameplayTagList=(Tag="Ability.Magic.Support.Heal",DevComment="Primary Heal ability")
+GameplayTagList=(Tag="Ability.Magic.Utility.Teleport",DevComment="Primary Teleport ability")
+GameplayTagList=(Tag="Ability.Support.Heal",DevComment="Heal ability tag")
+GameplayTagList=(Tag="Ability.Utility.Teleport",DevComment="Teleport ability tag")
+GameplayTagList=(Tag="Cooldown.Magic.Fire",DevComment="Shared Fire magic cooldown category")
+GameplayTagList=(Tag="Cooldown.Magic.Support",DevComment="Shared support magic cooldown category")
+GameplayTagList=(Tag="Cooldown.Magic.Utility",DevComment="Shared utility magic cooldown category")

